def validations_add_institution(content):
    #validations of the content
    content["institution_id_type_code"]           =   str(content["institution_id_type_code"])
    content["institution_id_type_desc"]           =   str(content["institution_id_type_desc"])
    content["institution_id_code"     ]           =   str(content["institution_id_code"])
    content["fiid"                    ]           =   str(content["fiid"])              
    content["institution_id_desc"     ]           =   str(content["institution_id_desc"])
    return content


def validations_add_terminal(content):
    content["TerminalId"               ]   =      str(content["TerminalId"])
    content["SerialNumber"             ]   =      str(content["SerialNumber"])
    content["EntityId"                 ]   =      str(content["EntityId"])
    content["OwnerEntityId"            ]   =      str(content["OwnerEntityId"])
    content["TerminalUsage"            ]   =      str(content["TerminalUsage"])
    content["Factory"                  ]   =      str(content["Factory"])
    content["Telco"                    ]   =      str(content["Telco"])
    content["TimeOffset"               ]   =      int(content["TimeOffset"])
    content["RetailerId"               ]   =      str(content["RetailerId"])
    content["CompanyName"              ]   =      str(content["CompanyName"])
    content["Name"                     ]   =      str(content["Name"])
    content["CountryCode"              ]   =      str(content["CountryCode"])
    content["StateCode"                ]   =      str(content["StateCode"])
    content["CityCode"                 ]   =      str(content["CityCode"])
    content["CountyCode"               ]   =      int(content["CountyCode"])
    content["Address"                  ]   =      str(content["Address"])
    content["PostalCode"               ]   =      str(content["PostalCode"])
    content["Phone"                    ]   =      str(content["Phone"])
    content["CellPhone"                ]   =      str(content["CellPhone"])
    content["FaxPhone"                 ]   =      str(content["FaxPhone"])
    content["AfterHoursPhone"          ]   =      str(content["AfterHoursPhone"])
    content["AfterHoursCellPhone"      ]   =      str(content["AfterHoursCellPhone"])
    content["AfterHoursFaxPhone"       ]   =      str(content["AfterHoursFaxPhone"])
    content["ReferralPhone"            ]   =      str(content["ReferralPhone"])
    content["EmailAddress"             ]   =      str(content["EmailAddress"])
    content["AlternateEmailAddress"    ]   =      str(content["AlternateEmailAddress"])
    content["IdentificationTypeCode"   ]   =      int(content["IdentificationTypeCode"])
    content["IdentificationNumber"     ]   =      str(content["IdentificationNumber"])
    content["CutoverBalanceStart"      ]   =      int(content["CutoverBalanceStart"])
    content["CutoverBalanceEnd"        ]   =      int(content["CutoverBalanceEnd"])
    content["PostingDateCurrent"       ]   =      int(content["PostingDateCurrent"])
    content["InstalationDate"          ]   =      int(content["InstalationDate"])
    content["TimeOutCode"              ]   =      int(content["TimeOutCode"])
    content["LastUpdateDateNotMonetary"]   =      int(content["LastUpdateDateNotMonetary"])
    content["LastUpdateDateMonetary"   ]   =      int(content["LastUpdateDateMonetary"])
    content["StatusCode"               ]   =      int(content["StatusCode"])
    return content


def validations_add_bin(content):
    content["LowRange"         ] =  int(content["LowRange"         ])
    content["Filler0"          ] =  int(content["Filler0"          ])
    content["HighRange"        ] =  int(content["HighRange"        ])
    content["Filler1"          ] =  int(content["Filler1"          ])
    content["ProductId"        ] =  int(content["ProductId"        ])
    content["ProductIdName"    ] =  str(content["ProductIdName"    ])
    content["EntityId"         ] =  str(content["EntityId"         ])
    content["BinCode"          ] =  int(content["BinCode"          ])
    content["MainBinCode"      ] =  int(content["MainBinCode"      ])
    content["CheckDigitCode"   ] =  int(content["CheckDigitCode"   ])
    content["LengthCode"       ] =  str(content["LengthCode"       ])
    content["TypeCode"         ] =  str(content["TypeCode"         ])
    content["UsageCode"        ] =  int(content["UsageCode"        ])
    content["DomainCode"       ] =  int(content["DomainCode"       ])
    content["BinProcessorCode" ] =  int(content["BinProcessorCode" ])
    content["CountryCode"      ] =  str(content["CountryCode"      ])
    content["AuthTypeCode"     ] =  int(content["AuthTypeCode"     ])
    content["StandInCode"      ] =  int(content["StandInCode"      ])
    content["TimeOutCode"      ] =  int(content["TimeOutCode"      ])
    content["ProcessNameCode"  ] =  str(content["ProcessNameCode"  ])
    return content


def validations_add_transaction(content):
    #validations of the content
    content["u_timestamp"                             ] =  int(content["u_timestamp"                           ])
    content["MessageType"                             ] =  str(content["MessageType"                           ])
    content["PrimaryBitMap"                           ] =  str(content["PrimaryBitMap"                         ])
    content["SecondaryBitMap"                         ] =  str(content["SecondaryBitMap"                       ])
    content["PrimaryAccountNumberPAN"                 ] =  str(content["PrimaryAccountNumberPAN"               ])
    content["ProcessingCode"                          ] =  str(content["ProcessingCode"                        ])
    content["TransactionAmount"                       ] =  str(content["TransactionAmount"                     ])
    content["TransactionAmountCardholderBilling"      ] =  str(content["TransactionAmountCardholderBilling"    ])
    content["TransmissionDateandTime"                 ] =  str(content["TransmissionDateandTime"               ])
    content["ConversionRateCardholderBilling"         ] =  str(content["ConversionRateCardholderBilling"       ])
    content["SystemsTraceAuditNumber"                 ] =  str(content["SystemsTraceAuditNumber"               ])
    content["LocalTransactionTime"                    ] =  str(content["LocalTransactionTime"                  ])
    content["LocalTransactionDate"                    ] =  str(content["LocalTransactionDate"                  ])
    content["ExpirationDate"                          ] =  str(content["ExpirationDate"                        ])
    content["SettlementDate"                          ] =  str(content["SettlementDate"                        ])
    content["CaptureDate"                             ] =  str(content["CaptureDate"                           ])
    content["MerchantTypeCode"                        ] =  str(content["MerchantTypeCode"                      ])
    content["AcquirerInstitutionCountryCode"          ] =  str(content["AcquirerInstitutionCountryCode"        ])
    content["IssuerInstututionCountryCode"            ] =  str(content["IssuerInstututionCountryCode"          ])
    content["ForwardingInstitutionCountryCode"        ] =  str(content["ForwardingInstitutionCountryCode"      ])
    content["PointofServiceEntryModeCode"             ] =  str(content["PointofServiceEntryModeCode"           ])
    content["CardSequenceNumber"                      ] =  str(content["CardSequenceNumber"                    ])
    content["NetworkInternationalIdentifierCode"      ] =  str(content["NetworkInternationalIdentifierCode"    ])
    content["PointofServiceConditionCode"             ] =  str(content["PointofServiceConditionCode"           ])
    content["AcquiringInstitutionIdentification"      ] =  str(content["AcquiringInstitutionIdentification"    ])
    content["ForwardingInstitutionIdentification"     ] =  str(content["ForwardingInstitutionIdentification"   ])
    content["Track2Data"                              ] =  str(content["Track2Data"                            ])
    content["RetrievalReferenceNumber"                ] =  str(content["RetrievalReferenceNumber"              ])
    content["AuthorizationIdentificationResponse"     ] =  str(content["AuthorizationIdentificationResponse"   ])
    content["ResponseCode"                            ] =  str(content["ResponseCode"                          ])
    content["CardAcceptorTerminalIdentification"      ] =  str(content["CardAcceptorTerminalIdentification"    ])
    content["CardAcceptorIdentification"              ] =  str(content["CardAcceptorIdentification"            ])
    content["CardAcceptorNameLocation"                ] =  str(content["CardAcceptorNameLocation"              ])
    content["Track1Data"                              ] =  str(content["Track1Data"                            ])
    content["RetailerData"                            ] =  str(content["RetailerData"                          ])
    content["TransactionCurrencyCode"                 ] =  str(content["TransactionCurrencyCode"               ])
    content["CurrencyCodeCardholderBilling"           ] =  str(content["CurrencyCodeCardholderBilling"         ])
    content["PersonalIdentificationNumberPINData"     ] =  str(content["PersonalIdentificationNumberPINData"   ])
    content["AdditionalAmount"                        ] =  str(content["AdditionalAmount"                      ])
    content["IntegratedCircuitCardICC"                ] =  str(content["IntegratedCircuitCardICC"              ])
    content["CardholdersIdentificationNumberandName"  ] =  str(content["CardholdersIdentificationNumberandName"])
    content["AdditionalAmounts"                       ] =  str(content["AdditionalAmounts"                     ])
    content["TerminalData"                            ] =  str(content["TerminalData"                          ])
    content["CardData"                                ] =  str(content["CardData"                              ])
    content["TerminalPostalCode"                      ] =  str(content["TerminalPostalCode"                    ])
    content["Token1"                                  ] =  str(content["Token1"                                ])
    content["Token2"                                  ] =  str(content["Token2"                                ])
    content["Token3"                                  ] =  str(content["Token3"                                ])
    content["PrimaryMessageAuthenticationCodeMAC"     ] =  str(content["PrimaryMessageAuthenticationCodeMAC"   ])
    return content


def validations_add_retailer(content):
    content["RetailerId"                        ]  =  str(content["RetailerId"                        ])
    content["EntityId"                          ]  =  str(content["EntityId"                          ])
    content["GroupCode"                         ]  =  int(content["GroupCode"                         ])
    content["MallCode"                          ]  =  int(content["MallCode"                          ])
    content["AcquirerRegionCode"                ]  =  str(content["AcquirerRegionCode"                ])
    content["CompanyName"                       ]  =  str(content["CompanyName"                       ])
    content["Name"                              ]  =  str(content["Name"                              ])
    content["CountryCode"                       ]  =  str(content["CountryCode"                       ])
    content["StateCode"                         ]  =  str(content["StateCode"                         ])
    content["CityCode"                          ]  =  int(content["CityCode"                          ])
    content["CountyCode"                        ]  =  int(content["CountyCode"                        ])
    content["Address"                           ]  =  str(content["Address"                           ])
    content["PostalCode"                        ]  =  str(content["PostalCode"                        ])
    content["Phone"                             ]  =  str(content["Phone"                             ])
    content["CellPhone"                         ]  =  str(content["CellPhone"                         ])
    content["FaxPhone"                          ]  =  str(content["FaxPhone"                          ])
    content["AfterHoursPhone"                   ]  =  str(content["AfterHoursPhone"                   ])
    content["AfterHoursCellPhone"               ]  =  str(content["AfterHoursCellPhone"               ])
    content["AfterHoursFaxPhone"                ]  =  str(content["AfterHoursFaxPhone"                ])
    content["ReferralPhone"                     ]  =  str(content["ReferralPhone"                     ])
    content["EmailAddress"                      ]  =  str(content["EmailAddress"                      ])
    content["AlternateEmailAddress"             ]  =  str(content["AlternateEmailAddress"             ])
    content["IdentificationTypeCode"            ]  =  int(content["IdentificationTypeCode"            ])
    content["IdentificationNumber"              ]  =  str(content["IdentificationNumber"              ])
    content["MCC"                               ]  =  int(content["MCC"                               ])
    content["MCCForNoPresentTransaction"        ]  =  int(content["MCCForNoPresentTransaction"        ])
    content["IdForAmex"                         ]  =  str(content["IdForAmex"                         ])
    content["MCCForAmex"                        ]  =  int(content["MCCForAmex"                        ])
    content["MCCForAmexForNoPresentTransaction" ]  =  int(content["MCCForAmexForNoPresentTransaction" ])
    content["WorkingHoursCode"                  ]  =  int(content["WorkingHoursCode"                  ])
    content["DepositOnLineCode"                 ]  =  int(content["DepositOnLineCode"                 ])
    content["PaymentVendorsCode"                ]  =  int(content["PaymentVendorsCode"                ])
    content["AffiliationDate"                   ]  =  int(content["AffiliationDate"                   ])
    content["LastUpdateDateNotMonetary"         ]  =  int(content["LastUpdateDateNotMonetary"         ])
    content["LastUpdateDateMonetary"            ]  =  int(content["LastUpdateDateMonetary"            ])
    content["StatusCode"                        ]  =  int(content["StatusCode"                        ])
    return content


def validations_add_retailer_account(content):
    content["RetailerId"                 ]  =  str(content["RetailerId"               ]) 
    content["TerminalId"                 ]  =  str(content["TerminalId"               ]) 
    content["CardProductId"              ]  =  str(content["CardProductId"            ]) 
    content["AcquirerId"                 ]  =  int(content["AcquirerId"               ]) 
    content["PaymentBankInstitutionId"   ]  =  int(content["PaymentBankInstitutionId" ]) 
    content["AccountTypeCode"            ]  =  int(content["AccountTypeCode"          ]) 
    content["AccountNumber"              ]  =  int(content["AccountNumber"            ]) 
    content["StatusCode"                 ]  =  int(content["StatusCode"               ]) 
    content["RetefuenteCode"             ]  =  int(content["RetefuenteCode"           ]) 
    content["Retefuente"                 ]  =  float(content["Retefuente"             ]) 
    content["ReteicaCode"                ]  =  int(content["ReteicaCode"              ]) 
    content["Reteica"                    ]  =  float(content["Reteica"                ]) 
    content["CreeCode"                   ]  =  int(content["CreeCode"                 ]) 
    content["Cree"                       ]  =  float(content["Cree"                   ]) 
    content["ImpoconsumoCode"            ]  =  int(content["ImpoconsumoCode"          ]) 
    content["Impoconsumo"                ]  =  float(content["Impoconsumo"            ]) 
    content["CreeCode"                   ]  =  int(content["CreeCode"                 ]) 
    content["Cree"                       ]  =  float(content["Cree"                   ]) 
    content["ReteivaCode"                ]  =  int(content["ReteivaCode"              ]) 
    content["Reteiva"                    ]  =  float(content["Reteiva"                ]) 
    return content


def validations_add_retailer_rule(content):
    content["RetailerId"                          ]  =   str(content["RetailerId"                         ]) 
    content["TerminalId"                          ]  =   str(content["TerminalId"                         ]) 
    content["CardProductId"                       ]  =   int(content["CardProductId"                      ]) 
    content["FullTransactionCode"                 ]  =   str(content["FullTransactionCode"                ]) 
    content["AmountLowRange"                      ]  =   int(content["AmountLowRange"                     ]) 
    content["AmountHighRange"                     ]  =   int(content["AmountHighRange"                    ]) 
    content["IvaCode"                             ]  =   int(content["IvaCode"                            ]) 
    content["Iva"                                 ]  =   float(content["Iva"                              ]) 
    content["TipCode"                             ]  =   int(content["TipCode"                            ]) 
    content["TipMaximum"                          ]  =   float(content["TipMaximum"                       ]) 
    content["AirportTaxCode"                      ]  =   int(content["AirportTaxCode"                     ]) 
    content["AirportTaxMaximum"                   ]  =   float(content["AirportTaxMaximum"                ]) 
    content["CashBackCode"                        ]  =   int(content["CashBackCode"                       ]) 
    content["CashBackMaximum"                     ]  =   float(content["CashBackMaximum"                  ]) 
    content["DonationCode"                        ]  =   int(content["DonationCode"                       ]) 
    content["DonationMaximum"                     ]  =   float(content["DonationMaximum"                  ]) 
    content["SurchargeCode"                       ]  =   int(content["SurchargeCode"                      ]) 
    content["SurchargeMaximum"                    ]  =   float(content["SurchargeMaximum"                 ]) 
    content["CurrencyConversionCode"              ]  =   int(content["CurrencyConversionCode"             ]) 
    content["CurrencyConversionMaximum"           ]  =   float(content["CurrencyConversionMaximum"        ]) 
    content["CostPerTransactionCode"              ]  =   int(content["CostPerTransactionCode"             ]) 
    content["CostPerTransactionMaximum"           ]  =   float(content["CostPerTransactionMaximum"        ]) 
    content["UserInterchangeFixedValueCode"       ]  =   int(content["UserInterchangeFixedValueCode"      ]) 
    content["UserInterchangeFixedValue"           ]  =   float(content["UserInterchangeFixedValue"        ]) 
    content["UserInterchangeCommissionCode"       ]  =   int(content["UserInterchangeCommissionCode"      ]) 
    content["UserInterchangeCommission"           ]  =   float(content["UserInterchangeCommission"        ]) 
    content["UserAcquirerFixedValueCode"          ]  =   int(content["UserAcquirerFixedValueCode"         ]) 
    content["UserAcquirerFixedValue"              ]  =   float(content["UserAcquirerFixedValue"           ]) 
    content["UserAcquirerCommissionCode"          ]  =   int(content["UserAcquirerCommissionCode"         ]) 
    content["UserAcquirerCommission"              ]  =   float(content["UserAcquirerCommission"           ]) 
    content["UserProcessorFixedValueCode"         ]  =   int(content["UserProcessorFixedValueCode"        ]) 
    content["UserProcessorFixedValue"             ]  =   float(content["UserProcessorFixedValue"          ]) 
    content["UserProcessorCommissionCode"         ]  =   int(content["UserProcessorCommissionCode"        ]) 
    content["UserProcessorCommission"             ]  =   float(content["UserProcessorCommission"          ]) 
    content["RetailerInterchangeFixedValueCode"   ]  =   int(content["RetailerInterchangeFixedValueCode"  ]) 
    content["RetailerInterchangeFixedValue"       ]  =   float(content["RetailerInterchangeFixedValue"    ]) 
    content["RetailerInterchangeCommissionCode"   ]  =   int(content["RetailerInterchangeCommissionCode"  ]) 
    content["RetailerInterchangeCommission"       ]  =   float(content["RetailerInterchangeCommission"    ]) 
    content["RetailerAcquirerFixedValueCode"      ]  =   int(content["RetailerAcquirerFixedValueCode"     ]) 
    content["RetailerAcquirerFixedValue"          ]  =   float(content["RetailerAcquirerFixedValue"       ]) 
    content["RetailerAcquirerCommissionCode"      ]  =   int(content["RetailerAcquirerCommissionCode"     ]) 
    content["RetailerAcquirerCommission"          ]  =   float(content["RetailerAcquirerCommission"       ]) 
    content["RetailerProcessorFixedValueCode"     ]  =   int(content["RetailerProcessorFixedValueCode"    ]) 
    content["RetailerProcessorFixedValue"         ]  =   float(content["RetailerProcessorFixedValue"      ]) 
    content["RetailerProcessorCommissionCode"     ]  =   int(content["RetailerProcessorCommissionCode"    ]) 
    content["RetailerProcessorCommission"         ]  =   float(content["RetailerProcessorCommission"      ]) 
    content["HoldingDaysCode"                     ]  =   int(content["HoldingDaysCode"                    ]) 
    content["HoldingDays"                         ]  =   int(content["HoldingDays"                        ]) 
    content["CardLastFourDigitsCode"              ]  =   int(content["CardLastFourDigitsCode"             ]) 
    content["CardManualyDataEntryCode"            ]  =   int(content["CardManualyDataEntryCode"           ]) 
    content["CardNoPresentCode"                   ]  =   int(content["CardNoPresentCode"                  ]) 
    content["UserAuthenticationCode"              ]  =   int(content["UserAuthenticationCode"             ]) 
    content["FloorLimit"                          ]  =   int(content["FloorLimit"                         ]) 
    content["CeilingLimit"                        ]  =   int(content["CeilingLimit"                       ]) 
    return content


def validations_update_institution(content):
    content["institution_id_type_desc"]           =   str(content["institution_id_type_desc"])
    content["fiid"                    ]           =   str(content["fiid"])              
    content["institution_id_desc"     ]           =   str(content["institution_id_desc"])
    return content


def validations_update_terminal(content):
    content["SerialNumber"             ]   =      str(content["SerialNumber"])
    content["EntityId"                 ]   =      int(content["EntityId"])
    content["OwnerEntityId"            ]   =      int(content["OwnerEntityId"])
    content["TerminalUsage"            ]   =      str(content["TerminalUsage"])
    content["Factory"                  ]   =      str(content["Factory"])
    content["Telco"                    ]   =      str(content["Telco"])
    content["TimeOffset"               ]   =      int(content["TimeOffset"])
    content["RetailerId"               ]   =      str(content["RetailerId"])
    content["CompanyName"              ]   =      str(content["CompanyName"])
    content["Name"                     ]   =      str(content["Name"])
    content["CountryCode"              ]   =      str(content["CountryCode"])
    content["StateCode"                ]   =      str(content["StateCode"])
    content["CityCode"                 ]   =      str(content["CityCode"])
    content["CountyCode"               ]   =      int(content["CountyCode"])
    content["Address"                  ]   =      str(content["Address"])
    content["PostalCode"               ]   =      str(content["PostalCode"])
    content["Phone"                    ]   =      str(content["Phone"])
    content["CellPhone"                ]   =      str(content["CellPhone"])
    content["FaxPhone"                 ]   =      str(content["FaxPhone"])
    content["AfterHoursPhone"          ]   =      str(content["AfterHoursPhone"])
    content["AfterHoursCellPhone"      ]   =      str(content["AfterHoursCellPhone"])
    content["AfterHoursFaxPhone"       ]   =      str(content["AfterHoursFaxPhone"])
    content["ReferralPhone"            ]   =      str(content["ReferralPhone"])
    content["EmailAddress"             ]   =      str(content["EmailAddress"])
    content["AlternateEmailAddress"    ]   =      str(content["AlternateEmailAddress"])
    content["IdentificationTypeCode"   ]   =      int(content["IdentificationTypeCode"])
    content["IdentificationNumber"     ]   =      str(content["IdentificationNumber"])
    content["CutoverBalanceStart"      ]   =      int(content["CutoverBalanceStart"])
    content["CutoverBalanceEnd"        ]   =      int(content["CutoverBalanceEnd"])
    content["PostingDateCurrent"       ]   =      int(content["PostingDateCurrent"])
    content["InstalationDate"          ]   =      int(content["InstalationDate"])
    content["TimeOutCode"              ]   =      int(content["TimeOutCode"])
    content["LastUpdateDateNotMonetary"]   =      int(content["LastUpdateDateNotMonetary"])
    content["LastUpdateDateMonetary"   ]   =      int(content["LastUpdateDateMonetary"])
    content["StatusCode"               ]   =      int(content["StatusCode"])
    return content


def validations_update_bin(content):
    content["LowRange"         ] =  int(content["LowRange"         ])
    content["Filler0"          ] =  int(content["Filler0"          ])
    content["HighRange"        ] =  int(content["HighRange"        ])
    content["Filler1"          ] =  int(content["Filler1"          ])
    content["ProductIdName"    ] =  str(content["ProductIdName"    ])
    content["MainBinCode"      ] =  int(content["MainBinCode"      ])
    content["CheckDigitCode"   ] =  int(content["CheckDigitCode"   ])
    content["LengthCode"       ] =  str(content["LengthCode"       ])
    content["TypeCode"         ] =  str(content["TypeCode"         ])
    content["UsageCode"        ] =  int(content["UsageCode"        ])
    content["DomainCode"       ] =  int(content["DomainCode"       ])
    content["BinProcessorCode" ] =  int(content["BinProcessorCode" ])
    content["CountryCode"      ] =  str(content["CountryCode"      ])
    content["AuthTypeCode"     ] =  int(content["AuthTypeCode"     ])
    content["StandInCode"      ] =  int(content["StandInCode"      ])
    content["TimeOutCode"      ] =  int(content["TimeOutCode"      ])
    content["ProcessNameCode"  ] =  str(content["ProcessNameCode"  ])
    return content


def validations_update_transaction(content):
    content["u_timestamp"                             ] =  int(content["u_timestamp"                           ])
    content["MessageType"                             ] =  str(content["MessageType"                           ])
    content["PrimaryBitMap"                           ] =  str(content["PrimaryBitMap"                         ])
    content["SecondaryBitMap"                         ] =  str(content["SecondaryBitMap"                       ])
    content["TransactionAmount"                       ] =  str(content["TransactionAmount"                     ])
    content["TransactionAmountCardholderBilling"      ] =  str(content["TransactionAmountCardholderBilling"    ])
    content["TransmissionDateandTime"                 ] =  str(content["TransmissionDateandTime"               ])
    content["ConversionRateCardholderBilling"         ] =  str(content["ConversionRateCardholderBilling"       ])
    content["LocalTransactionTime"                    ] =  str(content["LocalTransactionTime"                  ])
    content["LocalTransactionDate"                    ] =  str(content["LocalTransactionDate"                  ])
    content["ExpirationDate"                          ] =  str(content["ExpirationDate"                        ])
    content["CaptureDate"                             ] =  str(content["CaptureDate"                           ])
    content["MerchantTypeCode"                        ] =  str(content["MerchantTypeCode"                      ])
    content["AcquirerInstitutionCountryCode"          ] =  str(content["AcquirerInstitutionCountryCode"        ])
    content["IssuerInstututionCountryCode"            ] =  str(content["IssuerInstututionCountryCode"          ])
    content["ForwardingInstitutionCountryCode"        ] =  str(content["ForwardingInstitutionCountryCode"      ])
    content["PointofServiceEntryModeCode"             ] =  str(content["PointofServiceEntryModeCode"           ])
    content["CardSequenceNumber"                      ] =  str(content["CardSequenceNumber"                    ])
    content["NetworkInternationalIdentifierCode"      ] =  str(content["NetworkInternationalIdentifierCode"    ])
    content["PointofServiceConditionCode"             ] =  str(content["PointofServiceConditionCode"           ])
    content["AcquiringInstitutionIdentification"      ] =  str(content["AcquiringInstitutionIdentification"    ])
    content["ForwardingInstitutionIdentification"     ] =  str(content["ForwardingInstitutionIdentification"   ])
    content["Track2Data"                              ] =  str(content["Track2Data"                            ])
    content["RetrievalReferenceNumber"                ] =  str(content["RetrievalReferenceNumber"              ])
    content["AuthorizationIdentificationResponse"     ] =  str(content["AuthorizationIdentificationResponse"   ])
    content["ResponseCode"                            ] =  str(content["ResponseCode"                          ])
    content["CardAcceptorTerminalIdentification"      ] =  str(content["CardAcceptorTerminalIdentification"    ])
    content["CardAcceptorIdentification"              ] =  str(content["CardAcceptorIdentification"            ])
    content["CardAcceptorNameLocation"                ] =  str(content["CardAcceptorNameLocation"              ])
    content["Track1Data"                              ] =  str(content["Track1Data"                            ])
    content["TransactionCurrencyCode"                 ] =  str(content["TransactionCurrencyCode"               ])
    content["CurrencyCodeCardholderBilling"           ] =  str(content["CurrencyCodeCardholderBilling"         ])
    content["PersonalIdentificationNumberPINData"     ] =  str(content["PersonalIdentificationNumberPINData"   ])
    content["AdditionalAmount"                        ] =  str(content["AdditionalAmount"                      ])
    content["IntegratedCircuitCardICC"                ] =  str(content["IntegratedCircuitCardICC"              ])
    content["CardholdersIdentificationNumberandName"  ] =  str(content["CardholdersIdentificationNumberandName"])
    content["AdditionalAmounts"                       ] =  str(content["AdditionalAmounts"                     ])
    content["TerminalData"                            ] =  str(content["TerminalData"                          ])
    content["CardData"                                ] =  str(content["CardData"                              ])
    content["TerminalPostalCode"                      ] =  str(content["TerminalPostalCode"                    ])
    content["Token1"                                  ] =  str(content["Token1"                                ])
    content["Token2"                                  ] =  str(content["Token2"                                ])
    content["Token3"                                  ] =  str(content["Token3"                                ])
    content["PrimaryMessageAuthenticationCodeMAC"     ] =  str(content["PrimaryMessageAuthenticationCodeMAC"   ])
    return content


def validations_update_retailer(content):
    content["EntityId"                          ]  =  str(content["EntityId"                          ])
    content["GroupCode"                         ]  =  int(content["GroupCode"                         ])
    content["MallCode"                          ]  =  int(content["MallCode"                          ])
    content["AcquirerRegionCode"                ]  =  str(content["AcquirerRegionCode"                ])
    content["CompanyName"                       ]  =  str(content["CompanyName"                       ])
    content["Name"                              ]  =  str(content["Name"                              ])
    content["CountryCode"                       ]  =  str(content["CountryCode"                       ])
    content["StateCode"                         ]  =  str(content["StateCode"                         ])
    content["CityCode"                          ]  =  int(content["CityCode"                          ])
    content["CountyCode"                        ]  =  int(content["CountyCode"                        ])
    content["Address"                           ]  =  str(content["Address"                           ])
    content["PostalCode"                        ]  =  str(content["PostalCode"                        ])
    content["Phone"                             ]  =  str(content["Phone"                             ])
    content["CellPhone"                         ]  =  str(content["CellPhone"                         ])
    content["FaxPhone"                          ]  =  str(content["FaxPhone"                          ])
    content["AfterHoursPhone"                   ]  =  str(content["AfterHoursPhone"                   ])
    content["AfterHoursCellPhone"               ]  =  str(content["AfterHoursCellPhone"               ])
    content["AfterHoursFaxPhone"                ]  =  str(content["AfterHoursFaxPhone"                ])
    content["ReferralPhone"                     ]  =  str(content["ReferralPhone"                     ])
    content["EmailAddress"                      ]  =  str(content["EmailAddress"                      ])
    content["AlternateEmailAddress"             ]  =  str(content["AlternateEmailAddress"             ])
    content["IdentificationTypeCode"            ]  =  int(content["IdentificationTypeCode"            ])
    content["IdentificationNumber"              ]  =  str(content["IdentificationNumber"              ])
    content["MCC"                               ]  =  int(content["MCC"                               ])
    content["MCCForNoPresentTransaction"        ]  =  int(content["MCCForNoPresentTransaction"        ])
    content["IdForAmex"                         ]  =  str(content["IdForAmex"                         ])
    content["MCCForAmex"                        ]  =  int(content["MCCForAmex"                        ])
    content["MCCForAmexForNoPresentTransaction" ]  =  int(content["MCCForAmexForNoPresentTransaction" ])
    content["WorkingHoursCode"                  ]  =  int(content["WorkingHoursCode"                  ])
    content["DepositOnLineCode"                 ]  =  int(content["DepositOnLineCode"                 ])
    content["PaymentVendorsCode"                ]  =  int(content["PaymentVendorsCode"                ])
    content["AffiliationDate"                   ]  =  int(content["AffiliationDate"                   ])
    content["LastUpdateDateNotMonetary"         ]  =  int(content["LastUpdateDateNotMonetary"         ])
    content["LastUpdateDateMonetary"            ]  =  int(content["LastUpdateDateMonetary"            ])
    content["StatusCode"                        ]  =  int(content["StatusCode"                        ])
    return content


def validations_update_retailer_account(content):
    content["AcquirerId"                 ]  =  int(content["AcquirerId"               ]) 
    content["PaymentBankInstitutionId"   ]  =  int(content["PaymentBankInstitutionId" ]) 
    content["AccountTypeCode"            ]  =  int(content["AccountTypeCode"          ]) 
    content["AccountNumber"              ]  =  int(content["AccountNumber"            ]) 
    content["StatusCode"                 ]  =  int(content["StatusCode"               ]) 
    content["RetefuenteCode"             ]  =  int(content["RetefuenteCode"           ]) 
    content["Retefuente"                 ]  =  float(content["Retefuente"             ]) 
    content["ReteicaCode"                ]  =  int(content["ReteicaCode"              ]) 
    content["Reteica"                    ]  =  float(content["Reteica"                ]) 
    content["CreeCode"                   ]  =  int(content["CreeCode"                 ]) 
    content["Cree"                       ]  =  float(content["Cree"                   ]) 
    content["ImpoconsumoCode"            ]  =  int(content["ImpoconsumoCode"          ]) 
    content["Impoconsumo"                ]  =  float(content["Impoconsumo"            ]) 
    content["CreeCode"                   ]  =  int(content["CreeCode"                 ]) 
    content["Cree"                       ]  =  float(content["Cree"                   ]) 
    content["ReteivaCode"                ]  =  int(content["ReteivaCode"              ]) 
    content["Reteiva"                    ]  =  float(content["Reteiva"                ]) 
    return content


def validations_update_retailer_rule(content):
    content["AmountLowRange"                      ]  =   int(content["AmountLowRange"                     ]) 
    content["AmountHighRange"                     ]  =   int(content["AmountHighRange"                    ]) 
    content["IvaCode"                             ]  =   int(content["IvaCode"                            ]) 
    content["Iva"                                 ]  =   float(content["Iva"                              ]) 
    content["TipCode"                             ]  =   int(content["TipCode"                            ]) 
    content["TipMaximum"                          ]  =   float(content["TipMaximum"                       ]) 
    content["AirportTaxCode"                      ]  =   int(content["AirportTaxCode"                     ]) 
    content["AirportTaxMaximum"                   ]  =   float(content["AirportTaxMaximum"                ]) 
    content["CashBackCode"                        ]  =   int(content["CashBackCode"                       ]) 
    content["CashBackMaximum"                     ]  =   float(content["CashBackMaximum"                  ]) 
    content["DonationCode"                        ]  =   int(content["DonationCode"                       ]) 
    content["DonationMaximum"                     ]  =   float(content["DonationMaximum"                  ]) 
    content["SurchargeCode"                       ]  =   int(content["SurchargeCode"                      ]) 
    content["SurchargeMaximum"                    ]  =   float(content["SurchargeMaximum"                 ]) 
    content["CurrencyConversionCode"              ]  =   int(content["CurrencyConversionCode"             ]) 
    content["CurrencyConversionMaximum"           ]  =   float(content["CurrencyConversionMaximum"        ]) 
    content["CostPerTransactionCode"              ]  =   int(content["CostPerTransactionCode"             ]) 
    content["CostPerTransactionMaximum"           ]  =   float(content["CostPerTransactionMaximum"        ]) 
    content["UserInterchangeFixedValueCode"       ]  =   int(content["UserInterchangeFixedValueCode"      ]) 
    content["UserInterchangeFixedValue"           ]  =   float(content["UserInterchangeFixedValue"        ]) 
    content["UserInterchangeCommissionCode"       ]  =   int(content["UserInterchangeCommissionCode"      ]) 
    content["UserInterchangeCommission"           ]  =   float(content["UserInterchangeCommission"        ]) 
    content["UserAcquirerFixedValueCode"          ]  =   int(content["UserAcquirerFixedValueCode"         ]) 
    content["UserAcquirerFixedValue"              ]  =   float(content["UserAcquirerFixedValue"           ]) 
    content["UserAcquirerCommissionCode"          ]  =   int(content["UserAcquirerCommissionCode"         ]) 
    content["UserAcquirerCommission"              ]  =   float(content["UserAcquirerCommission"           ]) 
    content["UserProcessorFixedValueCode"         ]  =   int(content["UserProcessorFixedValueCode"        ]) 
    content["UserProcessorFixedValue"             ]  =   float(content["UserProcessorFixedValue"          ]) 
    content["UserProcessorCommissionCode"         ]  =   int(content["UserProcessorCommissionCode"        ]) 
    content["UserProcessorCommission"             ]  =   float(content["UserProcessorCommission"          ]) 
    content["RetailerInterchangeFixedValueCode"   ]  =   int(content["RetailerInterchangeFixedValueCode"  ]) 
    content["RetailerInterchangeFixedValue"       ]  =   float(content["RetailerInterchangeFixedValue"    ]) 
    content["RetailerInterchangeCommissionCode"   ]  =   int(content["RetailerInterchangeCommissionCode"  ]) 
    content["RetailerInterchangeCommission"       ]  =   float(content["RetailerInterchangeCommission"    ]) 
    content["RetailerAcquirerFixedValueCode"      ]  =   int(content["RetailerAcquirerFixedValueCode"     ]) 
    content["RetailerAcquirerFixedValue"          ]  =   float(content["RetailerAcquirerFixedValue"       ]) 
    content["RetailerAcquirerCommissionCode"      ]  =   int(content["RetailerAcquirerCommissionCode"     ]) 
    content["RetailerAcquirerCommission"          ]  =   float(content["RetailerAcquirerCommission"       ]) 
    content["RetailerProcessorFixedValueCode"     ]  =   int(content["RetailerProcessorFixedValueCode"    ]) 
    content["RetailerProcessorFixedValue"         ]  =   float(content["RetailerProcessorFixedValue"      ]) 
    content["RetailerProcessorCommissionCode"     ]  =   int(content["RetailerProcessorCommissionCode"    ]) 
    content["RetailerProcessorCommission"         ]  =   float(content["RetailerProcessorCommission"      ]) 
    content["HoldingDaysCode"                     ]  =   int(content["HoldingDaysCode"                    ]) 
    content["HoldingDays"                         ]  =   int(content["HoldingDays"                        ]) 
    content["CardLastFourDigitsCode"              ]  =   int(content["CardLastFourDigitsCode"             ]) 
    content["CardManualyDataEntryCode"            ]  =   int(content["CardManualyDataEntryCode"           ]) 
    content["CardNoPresentCode"                   ]  =   int(content["CardNoPresentCode"                  ]) 
    content["UserAuthenticationCode"              ]  =   int(content["UserAuthenticationCode"             ]) 
    content["FloorLimit"                          ]  =   int(content["FloorLimit"                         ]) 
    content["CeilingLimit"                        ]  =   int(content["CeilingLimit"                       ]) 
    return content
