name: Merge branches
on:
  push:
    branches:
      - 'QA'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: QA
          target_branch: main
          github_token: $Ci_Demo